#ifndef REPLIES_HPP
#define REPLIES_HPP

#include <string>

#define PREFIX      std::string(":irc.server ")
#define CRLF        std::string("\r\n")

#define ERR_NOSUCHNICK(nick, target)                   (PREFIX + "401 " + nick + " " + target + " :No such nick/channel" + CRLF)
#define ERR_NOSUCHSERVER(nick, server)                 (PREFIX + "402 " + nick + " " + server + " :No such server" + CRLF)
#define ERR_NOSUCHCHANNEL(nick, channel)               (PREFIX + "403 " + nick + " " + channel + " :No such channel" + CRLF)
#define ERR_CANNOTSENDTOCHAN(nick, channel)            (PREFIX + "404 " + nick + " " + channel + " :Cannot send to channel" + CRLF)
#define ERR_TOOMANYCHANNELS(nick, channel)             (PREFIX + "405 " + nick + " " + channel + " :You have joined too many channels" + CRLF)
#define ERR_WASNOSUCHNICK(nick, target)                (PREFIX + "406 " + nick + " " + target + " :There was no such nickname" + CRLF)
#define ERR_TOOMANYTARGETS(nick, target)               (PREFIX + "407 " + nick + " " + target + " :Too many targets" + CRLF)
#define ERR_NOSUCHSERVICE(nick, service)               (PREFIX + "408 " + nick + " " + service + " :No such service" + CRLF)
#define ERR_NOORIGIN(nick)                             (PREFIX + "409 " + nick + " :No origin specified" + CRLF)
#define ERR_NORECIPIENT(nick, cmd)                     (PREFIX + "411 " + nick + " :No recipient given (" + cmd + ")" + CRLF)
#define ERR_NOTEXTTOSEND(nick)                         (PREFIX + "412 " + nick + " :No text to send" + CRLF)
#define ERR_NOTOPLEVEL(nick, mask)                     (PREFIX + "413 " + nick + " " + mask + " :No toplevel domain specified" + CRLF)
#define ERR_WILDTOPLEVEL(nick, mask)                   (PREFIX + "414 " + nick + " " + mask + " :Wildcard in toplevel domain" + CRLF)
#define ERR_UNKNOWNCOMMAND(nick, cmd)                  (PREFIX + "421 " + nick + " " + cmd + " :Unknown command" + CRLF)
#define ERR_NOMOTD(nick)                               (PREFIX + "422 " + nick + " :MOTD File is missing" + CRLF)
#define ERR_NOADMININFO(nick, server)                  (PREFIX + "423 " + nick + " " + server + " :No administrative info available" + CRLF)
#define ERR_FILEERROR(nick, fileop, file)              (PREFIX + "424 " + nick + " :File error doing " + fileop + " on " + file + CRLF)
#define ERR_NONICKNAMEGIVEN(nick)                      (PREFIX + "431 " + nick + " :No nickname given" + CRLF)
#define ERR_ERRONEUSNICKNAME(nick, badnick)            (PREFIX + "432 " + nick + " " + badnick + " :Erroneous nickname" + CRLF)
#define ERR_NICKNAMEINUSE(nick, target)                (PREFIX + "433 " + nick + " " + target + " :Nickname is already in use" + CRLF)
#define ERR_NICKCOLLISION(nick, target)                (PREFIX + "436 " + nick + " " + target + " :Nickname collision KILL" + CRLF)
#define ERR_UNAVAILRESOURCE(nick, resource)            (PREFIX + "437 " + nick + " " + resource + " :Resource temporarily unavailable" + CRLF)
#define ERR_USERNOTINCHANNEL(nick, target, ch)         (PREFIX + "441 " + nick + " " + target + " " + ch + " :They aren't on that channel" + CRLF)
#define ERR_NOTONCHANNEL(nick, channel)                (PREFIX + "442 " + nick + " " + channel + " :You're not on that channel" + CRLF)
#define ERR_USERONCHANNEL(nick, target, ch)            (PREFIX + "443 " + nick + " " + target + " " + ch + " :is already on channel" + CRLF)
#define ERR_NOLOGIN(nick, user)                        (PREFIX + "444 " + nick + " " + user + " :User not logged in" + CRLF)
#define ERR_SUMMONDISABLED(nick)                       (PREFIX + "445 " + nick + " :SUMMON has been disabled" + CRLF)
#define ERR_USERSDISABLED(nick)                        (PREFIX + "446 " + nick + " :USERS has been disabled" + CRLF)
#define ERR_NOTREGISTERED(nick)                        (PREFIX + "451 " + nick + " :You have not registered" + CRLF)
#define ERR_NEEDMOREPARAMS(nick, cmd)                  (PREFIX + "461 " + nick + " " + cmd + " :Not enough parameters" + CRLF)
#define ERR_ALREADYREGISTERED(nick)                    (PREFIX + "462 " + nick + " :You may not reregister" + CRLF)
#define ERR_NOPERMFORHOST(nick)                        (PREFIX + "463 " + nick + " :Your host isn't among the privileged" + CRLF)
#define ERR_PASSWDMISMATCH(nick)                       (PREFIX + "464 " + nick + " :Password incorrect" + CRLF)
#define ERR_YOUREBANNEDCREEP(nick)                     (PREFIX + "465 " + nick + " :You are banned from this server" + CRLF)
#define ERR_KEYSET(nick, channel)                      (PREFIX + "467 " + nick + " " + channel + " :Channel key already set" + CRLF)
#define ERR_CHANNELISFULL(nick, channel)               (PREFIX + "471 " + nick + " " + channel + " :Cannot join channel (+l)" + CRLF)
#define ERR_UNKNOWNMODE(nick, modechar, channel)       (PREFIX + "472 " + nick + " " + modechar + " :is unknown mode char to me for " +  channel + CRLF)
#define ERR_INVITEONLYCHAN(nick, channel)              (PREFIX + "473 " + nick + " " + channel + " :Cannot join channel (+i)" + CRLF)
#define ERR_BANNEDFROMCHAN(nick, channel)              (PREFIX + "474 " + nick + " " + channel + " :Cannot join channel (+b)" + CRLF)
#define ERR_BADCHANNELKEY(nick, channel)               (PREFIX + "475 " + nick + " " + channel + " :Cannot join channel (+k)" + CRLF)
#define ERR_BADCHANMASK(nick, channel)                 (PREFIX + "476 " + nick + " " + channel + " :Bad Channel Mask" + CRLF)
#define ERR_NOCHANMODES(nick, channel)                 (PREFIX + "477 " + nick + " " + channel + " :Channel doesn't support modes" + CRLF)
#define ERR_BANLISTFULL(nick, channel, mode)           (PREFIX + "478 " + nick + " " + channel + " " + mode + " :Ban list is full" + CRLF)
#define ERR_NOPRIVILEGES(nick)                         (PREFIX + "481 " + nick + " :Permission Denied- You're not an IRC operator" + CRLF)
#define ERR_CHANOPRIVSNEEDED(nick, channel)            (PREFIX + "482 " + nick + " " + channel + " :You're not channel operator" + CRLF)
#define ERR_CANTKILLSERVER(nick)                       (PREFIX + "483 " + nick + " :You can't kill a server!" + CRLF)
#define ERR_RESTRICTED(nick)                           (PREFIX + "484 " + nick + " :Your connection is restricted!" + CRLF)
#define ERR_UNIQOPPRIVSNEEDED(nick)                    (PREFIX + "485 " + nick + " :You're not the original channel operator" + CRLF)
#define ERR_NOOPERHOST(nick)                           (PREFIX + "491 " + nick + " :No O-lines for your host" + CRLF)
#define ERR_UMODEUNKNOWNFLAG(nick)                     (PREFIX + "501 " + nick + " :Unknown MODE flag" + CRLF)
#define ERR_USERSDONTMATCH(nick)                       (PREFIX + "502 " + nick + " :Cannot change mode for other users" + CRLF)
#define ERR_INVALIDKEY(nick, channel)	               (PREFIX + "525 " + nick + " " + channel + " :Key is not well-formed" + CRLF)
#define ERR_INVALIDMODEPARAM(nk, ch, m, param, msg)    (PREFIX + "696 " + nk + " " + ch + " " + m + " " + param + " " + ch + " :" + msg + CRLF)


#define RPL_WELCOME(nick, user, host)                  (PREFIX + "001 " + nick + " :Welcome to the Internet Relay Network " + nick + "!" + user + "@" + host + CRLF)
#define RPL_YOURHOST(nick)                             (PREFIX + "002 " + nick + " :Your host is irc.server, running version 1.0" + CRLF)
#define RPL_CREATED(nick, creationTime)                (PREFIX + "003 " + nick + " :This server was created " + creationTime + CRLF)
#define RPL_MYINFO(nick)                               (PREFIX + "004 " + nick + " irc.server 1.0  iotkl" + CRLF)
#define RPL_NOTOPIC(nick, channel)                     (PREFIX + "331 " + nick + " " + channel + " :No topic is set" + CRLF)
#define RPL_TOPIC(nick, channel, topic)                (PREFIX + "332 " + nick + " " + channel + " :" + topic + CRLF)
#define RPL_TOPICWHOTIME(nick, ch, setter, t)          (PREFIX + "333 " + nick + " " + ch + " " + setter + " " + t + CRLF)
#define RPL_NAMREPLY(nick, channel, names)             (PREFIX + "353 " + nick + " = " + channel + " :" + names + CRLF)
#define RPL_ENDOFNAMES(nick, channel)                  (PREFIX + "366 " + nick + " " + channel + " :End of NAMES list" + CRLF)
#define RPL_MOTD(nick, text)                           (PREFIX + "372 " + nick + " :- " + text + CRLF)
#define RPL_MOTDSTART(nick)                            (PREFIX + "375 " + nick + " :- irc.server Message of the Day - " + CRLF)
#define RPL_ENDOFMOTD(nick)                            (PREFIX + "376 " + nick + " :End of /MOTD command" + CRLF)
#define RPL_UMODEIS(nick, modes)                       (PREFIX + "221 " + nick + " " + modes + CRLF)
#define RPL_CHANNELMODEIS(nick, ch, modes)             (PREFIX + "324 " + nick + " " + ch + " " + modes + CRLF)
#define RPL_CREATIONTIME(nick, ch, time)               (PREFIX + "329 " + nick + " " + ch + " " + time + CRLF)
#define RPL_INVITING(nick, target, channel)            (PREFIX + "341 " + nick + " " + target + " " + channel + CRLF)


#define RPL_NEWTOPIC(nick, channel, topic)             (nick + " TOPIC " + channel + " :" + topic + CRLF)
#define RPL_JOIN(user, channel)                        (user + " JOIN " + channel + CRLF)
#define RPL_PART(nk, ch, reason)                       (nk  + " PART " + ch + reason + CRLF)
#define RPL_QUIT(user, reason)                         (user + " QUIT :" + reason + CRLF)
#define RPL_PRIVMSG(sender, target, msg)               (sender + " PRIVMSG " + target + " :" + msg + CRLF)
#define RPL_NOTICE(sender, target, msg)                (sender + " NOTICE " + target + " :" + msg + CRLF)
#define RPL_NICK(oldnick, newnick)                     (oldnick + " NICK :" + newnick + CRLF)
#define RPL_KICK(by, channel, target, reason)          (by + " KICK " + channel + " " + target + " :" + reason + CRLF)
#define RPL_INVITE(by, target, channel)                (by + " INVITE " + target + " :" + channel + CRLF)
#define RPL_MODE(source, target, modes)                (source + " MODE " + target + " " + modes + CRLF)
#define RPL_PING(server)                               (server + " PONG " + server + CRLF)

#endif
